#cron: 0 0 0 * * *

odm:
  cache.folder.path: /workspace/cache
#  incompleteforms.allowed: true
#  subjectkeys.hashed: false
  file.path: /workspace/input/ODM.xml
#  redcap.api:
#    url: http://redcap/api/
#    token: 12345ABCDE67890ABCDE12345ABCDEF0
#    patientspercall: 1
#    key:
#      file.path: /some/path/client_certificate.p12
#      password: change-password
#  dis.rest:
#    url: http://dis/m4export/resteasy/export
#    studyname: COVID_GECCO
#    username: gecco
#    password: gecco
#    key:
#      file.path: /some/path/client_certificate.p12
#      password: change-password

fhir:
#  encounters.enabled: true
#  updateascreate.enabled: true
#  validation:
#    enabled: true
#    codeerrors.ignored: false
#  errorhandling.strict: true
  folder.path: /workspace/output
#  server:
#    url: https://fhir-server:9443/fhir-server/api/v4/
#    basicauth:
#      username: fhiruser
#      password: change-password
#    oauth2:
#      token.url: https://keycloak:8443/auth/realms/fhir/protocol/openid-connect/token
#      client:
#        id: fhir
#        secret: 1234567890
#    key:
#      file.path: /some/path/client_certificate.p12
#      password: change-password
#  terminologyserver:
#    url: https://fhir-server:9443/fhir-server/api/v4/
#    basicauth:
#      username: fhiruser
#      password: change-password
#    oauth2:
#      token.url: https://keycloak:8443/auth/realms/fhir/protocol/openid-connect/token
#      client:
#        id: fhir
#        secret: 1234567890
#    key:
#      file.path: /some/path/client_certificate.p12
#      password: change-password
#  identifier:
#    assigner: Ein Fiktives Krankenhaus
#    system:
#      condition: https://ein.fiktives.krankenhaus/fhir/NamingSystem/conditionId
#      consent: https://ein.fiktives.krankenhaus/fhir/NamingSystem/consentId
#      diagnosticreport: https://ein.fiktives.krankenhaus/fhir/NamingSystem/diagnosticreportId
#      encounter: https://ein.fiktives.krankenhaus/fhir/NamingSystem/encounterId
#      immunization: https://ein.kfiktives.rankenhaus/fhir/NamingSystem/immunizationId
#      medicationstatement: https://ein.fiktives.krankenhaus/fhir/NamingSystem/medicationstatementId
#      observation: https://ein.fiktives.krankenhaus/fhir/NamingSystem/observationId
#      patient: https://ein.fiktives.krankenhaus/fhir/NamingSystem/patientId
#      procedure: https://ein.fiktives.krankenhaus/fhir/NamingSystem/procedureId
spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER_URL:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      client-id: odm2fhir
    security.protocol: ${SECURITY_PROTOCOL:PLAINTEXT}
    ssl:
      trust-store-type: PKCS12
      trust-store-location: file://${SSL_TRUST_STORE:/opt/kafka-certs/ca.p12}
      trust-store-password: ${SSL_TRUST_STORE_PASSWORD}
      key-store-type: PKCS12
      key-store-location: file://${SSL_KEY_STORE_FILE:/opt/kafka-certs/user.p12}
      key-store-password: ${SSL_KEY_STORE_PASSWORD}
    template:
      default-topic: ${KAFKA_OUTPUT_TOPIC:fhir.odm-gecco}
